import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/container/navbar";
import Footer from "@/components/container/Footer";

export const metadata: Metadata = {
  title: "Trans Sabawana",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className=""
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
